from typing import Protocol, Any

class IGameCollectionDbContext(Protocol):
    def add(self, obj: Any) -> None: ...
    async def commit(self) -> None: ...
    async def refresh(self, obj: Any) -> None: ...
    async def execute(self, statement: Any): ...
    def delete(self, obj: Any) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...